# Pipeline simple para análisis SCA
stages:
  - security-scan
  - security-consolidation

variables:
  REPORTS_DIR: "security-reports"
  # Configurar umbrales de seguridad
  MAX_CRITICAL: "0"    # Máximo de vulnerabilidades críticas permitidas
  MAX_HIGH: "5"        # Máximo de vulnerabilidades altas permitidas

before_script:
  - mkdir -p $REPORTS_DIR

# Template para artefactos mejorado
.artifacts_template: &artifacts_template
  artifacts:
    paths:
      - $REPORTS_DIR/
    reports:
      # Para integración con GitLab Security Dashboard
      sast: $REPORTS_DIR/gl-sast-report.json
      dependency_scanning: $REPORTS_DIR/gl-dependency-scanning-report.json
    expire_in: 30 days
    when: always
    expose_as: "Security Analysis Reports"
    
# Análisis con Trivy 
trivy-scan:
  stage: security-scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  <<: *artifacts_template
  before_script:
    - mkdir -p $REPORTS_DIR
    - apk add --no-cache jq curl
  script:
    - echo "🔍 Ejecutando análisis Trivy..."
    - trivy image --download-db-only

    # Análisis principal
    - |
      trivy filesystem . \
        --format json \
        --output $REPORTS_DIR/trivy-report.json \
        --severity HIGH,CRITICAL

    # Generar reporte compatible con GitLab Security
    - |
      trivy filesystem . \
        --format template \
        --template '@contrib/gitlab.tpl' \
        --output $REPORTS_DIR/gl-dependency-scanning-report.json \
        --severity HIGH,CRITICAL || echo "Template GitLab no disponible"

    # Reporte en tabla
    - |
      trivy filesystem . \
        --format table \
        --output $REPORTS_DIR/trivy-table.txt \
        --severity HIGH,CRITICAL

    # Generar SBOM
    - |
      trivy filesystem . \
        --format cyclonedx \
        --output $REPORTS_DIR/sbom.json

    # Crear reporte HTML para visualización
    - |
      trivy filesystem . \
        --format template \
        --template '@contrib/html.tpl' \
        --output $REPORTS_DIR/trivy-report.html \
        --severity HIGH,CRITICAL || echo "Template HTML no disponible"

    # Mostrar resumen
    - echo "📊 Resumen del análisis:"
    - cat $REPORTS_DIR/trivy-table.txt

    # Generar estadísticas detalladas y EVALUAR FALLO
    - |
      if [ -f "$REPORTS_DIR/trivy-report.json" ] && [ -s "$REPORTS_DIR/trivy-report.json" ]; then
        CRITICAL=$(cat $REPORTS_DIR/trivy-report.json | jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' 2>/dev/null || echo "0")
        HIGH=$(cat $REPORTS_DIR/trivy-report.json | jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' 2>/dev/null || echo "0")
        MEDIUM=$(cat $REPORTS_DIR/trivy-report.json | jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "MEDIUM")] | length' 2>/dev/null || echo "0")
        
        echo "🚨 Vulnerabilidades críticas encontradas: $CRITICAL (máx permitido: $MAX_CRITICAL)"
        echo "⚠️  Vulnerabilidades altas encontradas: $HIGH (máx permitido: $MAX_HIGH)"
        echo "📋 Vulnerabilidades medias encontradas: $MEDIUM"
        
        # Crear reporte detallado
        {
          echo "# Reporte de Análisis de Seguridad - $(date)"
          echo "## Resumen Ejecutivo"
          echo "- **Críticas:** $CRITICAL (límite: $MAX_CRITICAL)"
          echo "- **Altas:** $HIGH (límite: $MAX_HIGH)" 
          echo "- **Medias:** $MEDIUM"
          echo ""
          echo "## Distribución por Proyecto"
          echo "### Java (pom.xml)"
          echo "Vulnerabilidades: $(cat $REPORTS_DIR/trivy-report.json | jq '[.Results[] | select(.Target | contains("pom.xml")).Vulnerabilities[]?] | length' 2>/dev/null || echo "0")"
          echo ""
          echo "### Node.js (package-lock.json)"  
          echo "Vulnerabilidades: $(cat $REPORTS_DIR/trivy-report.json | jq '[.Results[] | select(.Target | contains("package-lock.json")).Vulnerabilities[]?] | length' 2>/dev/null || echo "0")"
          echo ""
          echo "## Detalle de Vulnerabilidades Críticas"
          cat $REPORTS_DIR/trivy-report.json | jq -r '.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL") | "- **\(.VulnerabilityID)**: \(.Title) (CVSS: \(.CVSS.nvd.V3Score // "N/A"))"' 2>/dev/null || echo "No se pudieron extraer detalles"
        } > $REPORTS_DIR/executive-summary.md
        
        cat $REPORTS_DIR/executive-summary.md
        
        # Generar métricas para badges
        echo "CRITICAL_COUNT=$CRITICAL" > $REPORTS_DIR/metrics.env
        echo "HIGH_COUNT=$HIGH" >> $REPORTS_DIR/metrics.env
        echo "TOTAL_COUNT=$((CRITICAL + HIGH))" >> $REPORTS_DIR/metrics.env
        
        # ⚠️ EVALUACIÓN DE POLÍTICA DE SEGURIDAD ⚠️
        FAIL_PIPELINE=0
        
        if [ "$CRITICAL" -gt "$MAX_CRITICAL" ]; then
          echo "❌ FALLO: Se encontraron $CRITICAL vulnerabilidades críticas (máximo permitido: $MAX_CRITICAL)"
          FAIL_PIPELINE=1
        fi
        
        if [ "$HIGH" -gt "$MAX_HIGH" ]; then
          echo "❌ FALLO: Se encontraron $HIGH vulnerabilidades altas (máximo permitido: $MAX_HIGH)"
          FAIL_PIPELINE=1
        fi
        
        if [ "$FAIL_PIPELINE" -eq 1 ]; then
          echo ""
          echo "🚫 PIPELINE FALLIDO POR POLÍTICA DE SEGURIDAD"
          echo "📋 Debes corregir las vulnerabilidades antes de continuar"
          exit 1
        else
          echo "✅ Pipeline aprobado - vulnerabilidades dentro de límites aceptables"
        fi
        
      else
        echo "⚠️  No se pudo procesar el archivo JSON o está vacío"
        echo "❌ FALLO: Error procesando resultados de seguridad"
        exit 1
      fi

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH